// Package domain generated by 'freedom new-project investment'
package domain

import (
	"testing"
)

// go test -timeout 1300s -run ^TestClsService_PrepareData$ investment/domain -v -count=1
func TestClsService_PrepareData(t *testing.T) {
	unitTest := getSatUnitTest()
	unitTest.Run()

	var service *ClsService
	unitTest.FetchService(&service)

	service.PrepareData()
}

func TestClsService_PrepareData2(t *testing.T) {
	t.Log("hello")
}
