// Package domain generated by 'freedom new-project investment'
package domain

import (
	"investment/adapter/repository"

	"github.com/8treenet/freedom"
)

func init() {
	freedom.Prepare(func(initiator freedom.Initiator) {
		initiator.BindService(func() *NasdaqService {
			return &NasdaqService{}
		})
		initiator.InjectController(func(ctx freedom.Context) (service *NasdaqService) {
			initiator.FetchService(ctx, &service)
			return
		})
	})
}

// NasdaqService 纳斯达克服务  .
type NasdaqService struct {
	Worker  freedom.Worker
	DefRepo *repository.Default
}
